[phases.setup]
nixPkgs = ['jdk17']
cmds = ['mkdir -p /root/.gradle']

[phases.build]
cmds = ['./gradlew build -Dorg.gradle.daemon=false --no-daemon --no-parallel --stacktrace']

[start]
cmd = 'java -Xmx256m -Dfile.encoding=UTF-8 -jar build/libs/*-all.jar'
stopSignal = "SIGINT" 