[build]
builder = "nixpacks"
buildCommand = "./gradlew build -Dorg.gradle.daemon=false --no-daemon --no-parallel --stacktrace"

[deploy]
startCommand = "java -Xmx256m -jar build/libs/*.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
enabled = false 